// <auto-generated />
namespace ExerciseTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddWorkoutReferenceInWorkoutExercise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWorkoutReferenceInWorkoutExercise));
        
        string IMigrationMetadata.Id
        {
            get { return "201510011504087_AddWorkoutReferenceInWorkoutExercise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
